name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/wukuili/syncflux.git /home/runner/go/src/github.com/toni-moreno/syncflux
    - name: Get dependencies
      run: |
        cd /home/runner/go/src/github.com/toni-moreno/syncflux
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Building the backend
      run:  |
        cd /home/runner/go/src/github.com/toni-moreno/syncflux 
        go run build.go build
        go run build.go pkg-min-tar
        go run build.go latest

    - name: Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: syncflux
        path: /home/runner/go/src
